project:
  type: website
  output-dir: docs

website:
  title: "Spatial Transcriptomics Browser with Quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cerulean
    toc: true



